// <auto-generated />
namespace PFE.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version107 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version107));
        
        string IMigrationMetadata.Id
        {
            get { return "201907011754460_version107"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
